### ISSUE TITLE
ECS task definition, ECS service

### ISSUE THREAD

**Issue by denstorti** [devopsacademyau/2020-feb-project1-group1#17]
- task definition:
    - custom wordpress image from ECR
    - using efs as volume and mounting `/var/www/html` inside wordpress container for persistent storage
      - no need for IAM authentication
    - wordpress database variables coming from ssm parameter store
    - memory 128
    - any IAM execution role if needed with only required permissions
  - ecs service:
    - type EC2
    - use custom task definition for wordpress
    - service type replica
    - deployment type rolling update or blue/green (first is easier, second is better)
    - at least 2 task definitions running at any point in time
  - initialise wordpress database when first runs a container

**Comment by denstorti** [comment]
```
 wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
```
